### ISSUE TITLE
Data Standards and Code Directories (asked by AH)

### ISSUE THREAD

**Issue by vijayg10** [sp-convergence/payments-interoperability-layer#1]
## **Goal**:
`As a` stakeholder

`I want to` create standard data models with code directories for the new payment interoperability layer API
  
`so that` adopters can use the content for the their implementations

**Acceptance Criteria**:
- [x] Data standards and code directories are available for payment interoperability layer API
- [ ] Format complies with AH example
- [ ] The APIs are published in a git repo with links

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] Understand the templates provided by AH team
- [ ] Create the following for the new payment interoperability layer API
  - [ ] Create standard data models
  - [ ] Create code directories
- [ ] Refactor the API specifications based on the new observations and improvements
- [ ] Publish the content in a git repository

**Done**
- [ ] Acceptance Criteria pass
- [ ] Documentation is updated

## **Pull Requests**:
- NA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: TBC
